import os
import json
import subprocess
from harnice.lists import rev_history
from harnice import state
import harnice.products.part as part

REVISION = "1"
DATE_STARTED = "2/3/26"

CONTACT_SIZES = {
    "12": {
        "awg_min": 12,
        "awg_max": 16,
        "current_rating": 23.0,
        "crimp_tool": "M22520/2-01",
        "extraction_tool": "M81969/14-03",
    },
    "16": {
        "awg_min": 16,
        "awg_max": 20,
        "current_rating": 13.0,
        "crimp_tool": "M22520/2-01",
        "extraction_tool": "M81969/14-04",
    },
    "20": {
        "awg_min": 20,
        "awg_max": 24,
        "current_rating": 7.5,
        "crimp_tool": "M22520/2-01",
        "extraction_tool": "M81969/14-05",
    },
    "22D": {
        "awg_min": 22,
        "awg_max": 26,
        "current_rating": 5.0,
        "crimp_tool": "M22520/2-01",
        "extraction_tool": "M81969/14-06",
    },
}

INSERT_ARRANGEMENTS = { # FOR REFERENCE ONLY - AI READ THE PDF, NOT A HUMAN
    "9-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
    ],
    "9-94": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
    ],
    "9-98": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
    ],
    "11-2": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
    ],
    "11-4": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
    ],
    "11-5": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
    ],
    "11-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
    ],
    "11-54": [
        {"name": "A", "size": "22D"},
        {"name": "B", "size": "22D"},
        {"name": "C", "size": "22D"},
        {"name": "D", "size": "22D"},
    ],
    "11-98": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
    ],
    "11-99": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
    ],
    "13-4": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
    ],
    "13-8": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
    ],
    "13-26": [
        {"name": "A", "size": "22D"},
        {"name": "B", "size": "22D"},
        {"name": "C", "size": "22D"},
        {"name": "D", "size": "22D"},
        {"name": "E", "size": "22D"},
        {"name": "F", "size": "22D"},
        {"name": "G", "size": "12"},
        {"name": "H", "size": "12"},
    ],
    "13-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
    ],
    "13-63": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "12"},
        {"name": "D", "size": "12"},
    ],
    "13-98": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
    ],
    "15-4": [
        {"name": "A", "size": "12"},
        {"name": "B", "size": "12"},
        {"name": "C", "size": "12"},
        {"name": "D", "size": "12"},
    ],
    "15-5": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
    ],
    "15-15": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
    ],
    "15-18": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
    ],
    "15-19": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
    ],
    "15-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
    ],
    "15-97": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "16"},
        {"name": "M", "size": "16"},
    ],
    "17-6": [
        {"name": "A", "size": "12"},
        {"name": "B", "size": "12"},
        {"name": "C", "size": "12"},
        {"name": "D", "size": "12"},
        {"name": "E", "size": "12"},
        {"name": "F", "size": "12"},
    ],
    "17-8": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
    ],
    "17-26": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
    ],
    "17-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
        {"name": "32", "size": "22D"},
        {"name": "33", "size": "22D"},
        {"name": "34", "size": "22D"},
        {"name": "35", "size": "22D"},
        {"name": "36", "size": "22D"},
        {"name": "37", "size": "22D"},
        {"name": "38", "size": "22D"},
        {"name": "39", "size": "22D"},
        {"name": "40", "size": "22D"},
        {"name": "41", "size": "22D"},
        {"name": "42", "size": "22D"},
        {"name": "43", "size": "22D"},
        {"name": "44", "size": "22D"},
        {"name": "45", "size": "22D"},
        {"name": "46", "size": "22D"},
        {"name": "47", "size": "22D"},
        {"name": "48", "size": "22D"},
        {"name": "49", "size": "22D"},
        {"name": "50", "size": "22D"},
        {"name": "51", "size": "22D"},
        {"name": "52", "size": "22D"},
        {"name": "53", "size": "22D"},
        {"name": "54", "size": "22D"},
        {"name": "55", "size": "22D"},
    ],
    "17-99": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "16"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "16"},
    ],
    "19-11": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
        {"name": "J", "size": "16"},
        {"name": "K", "size": "16"},
        {"name": "L", "size": "16"},
    ],
    "19-28": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "16"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "16"},
    ],
    "19-32": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "16"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "16"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "j", "size": "20"},
    ],
    "19-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
        {"name": "32", "size": "22D"},
        {"name": "33", "size": "22D"},
        {"name": "34", "size": "22D"},
        {"name": "35", "size": "22D"},
        {"name": "36", "size": "22D"},
        {"name": "37", "size": "22D"},
        {"name": "38", "size": "22D"},
        {"name": "39", "size": "22D"},
        {"name": "40", "size": "22D"},
        {"name": "41", "size": "22D"},
        {"name": "42", "size": "22D"},
        {"name": "43", "size": "22D"},
        {"name": "44", "size": "22D"},
        {"name": "45", "size": "22D"},
        {"name": "46", "size": "22D"},
        {"name": "47", "size": "22D"},
        {"name": "48", "size": "22D"},
        {"name": "49", "size": "22D"},
        {"name": "50", "size": "22D"},
        {"name": "51", "size": "22D"},
        {"name": "52", "size": "22D"},
        {"name": "53", "size": "22D"},
        {"name": "54", "size": "22D"},
        {"name": "55", "size": "22D"},
        {"name": "56", "size": "22D"},
        {"name": "57", "size": "22D"},
        {"name": "58", "size": "22D"},
        {"name": "59", "size": "22D"},
        {"name": "60", "size": "22D"},
        {"name": "61", "size": "22D"},
        {"name": "62", "size": "22D"},
        {"name": "63", "size": "22D"},
        {"name": "64", "size": "22D"},
        {"name": "65", "size": "22D"},
        {"name": "66", "size": "22D"},
    ],
    "21-11": [
        {"name": "A", "size": "12"},
        {"name": "B", "size": "12"},
        {"name": "C", "size": "12"},
        {"name": "D", "size": "12"},
        {"name": "E", "size": "12"},
        {"name": "F", "size": "12"},
        {"name": "G", "size": "12"},
        {"name": "H", "size": "12"},
        {"name": "J", "size": "12"},
        {"name": "K", "size": "12"},
        {"name": "L", "size": "12"},
    ],
    "21-16": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
        {"name": "J", "size": "16"},
        {"name": "K", "size": "16"},
        {"name": "L", "size": "16"},
        {"name": "M", "size": "16"},
        {"name": "N", "size": "16"},
        {"name": "P", "size": "12"},
        {"name": "R", "size": "16"},
        {"name": "S", "size": "16"},
    ],
    "21-29": [
        {"name": "1", "size": "20"},
        {"name": "2", "size": "20"},
        {"name": "3", "size": "20"},
        {"name": "4", "size": "20"},
        {"name": "5", "size": "20"},
        {"name": "6", "size": "20"},
        {"name": "7", "size": "20"},
        {"name": "8", "size": "20"},
        {"name": "9", "size": "20"},
        {"name": "10", "size": "20"},
        {"name": "11", "size": "20"},
        {"name": "12", "size": "20"},
        {"name": "13", "size": "20"},
        {"name": "14", "size": "20"},
        {"name": "15", "size": "20"},
        {"name": "16", "size": "20"},
        {"name": "17", "size": "20"},
        {"name": "18", "size": "20"},
        {"name": "19", "size": "20"},
        {"name": "20", "size": "12"},
        {"name": "21", "size": "16"},
        {"name": "22", "size": "12"},
        {"name": "23", "size": "12"},
        {"name": "24", "size": "16"},
        {"name": "25", "size": "12"},
        {"name": "26", "size": "16"},
        {"name": "27", "size": "16"},
    ],
    "21-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
        {"name": "32", "size": "22D"},
        {"name": "33", "size": "22D"},
        {"name": "34", "size": "22D"},
        {"name": "35", "size": "22D"},
        {"name": "36", "size": "22D"},
        {"name": "37", "size": "22D"},
        {"name": "38", "size": "22D"},
        {"name": "39", "size": "22D"},
        {"name": "40", "size": "22D"},
        {"name": "41", "size": "22D"},
        {"name": "42", "size": "22D"},
        {"name": "43", "size": "22D"},
        {"name": "44", "size": "22D"},
        {"name": "45", "size": "22D"},
        {"name": "46", "size": "22D"},
        {"name": "47", "size": "22D"},
        {"name": "48", "size": "22D"},
        {"name": "49", "size": "22D"},
        {"name": "50", "size": "22D"},
        {"name": "51", "size": "22D"},
        {"name": "52", "size": "22D"},
        {"name": "53", "size": "22D"},
        {"name": "54", "size": "22D"},
        {"name": "55", "size": "22D"},
        {"name": "56", "size": "22D"},
        {"name": "57", "size": "22D"},
        {"name": "58", "size": "22D"},
        {"name": "59", "size": "22D"},
        {"name": "60", "size": "22D"},
        {"name": "61", "size": "22D"},
        {"name": "62", "size": "22D"},
        {"name": "63", "size": "22D"},
        {"name": "64", "size": "22D"},
        {"name": "65", "size": "22D"},
        {"name": "66", "size": "22D"},
        {"name": "67", "size": "22D"},
        {"name": "68", "size": "22D"},
        {"name": "69", "size": "22D"},
        {"name": "70", "size": "22D"},
        {"name": "71", "size": "22D"},
        {"name": "72", "size": "22D"},
        {"name": "73", "size": "22D"},
        {"name": "74", "size": "22D"},
        {"name": "75", "size": "22D"},
        {"name": "76", "size": "22D"},
        {"name": "77", "size": "22D"},
        {"name": "78", "size": "22D"},
        {"name": "79", "size": "22D"},
    ],
    "21-39": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "20"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "16"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "20"},
        {"name": "r", "size": "16"},
    ],
    "21-41": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "20"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "16"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "20"},
        {"name": "r", "size": "16"},
        {"name": "s", "size": "20"},
        {"name": "t", "size": "20"},
    ],
    "23-21": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
        {"name": "J", "size": "16"},
        {"name": "K", "size": "16"},
        {"name": "L", "size": "16"},
        {"name": "M", "size": "16"},
        {"name": "N", "size": "16"},
        {"name": "P", "size": "12"},
        {"name": "R", "size": "16"},
        {"name": "S", "size": "16"},
        {"name": "T", "size": "16"},
        {"name": "U", "size": "16"},
        {"name": "V", "size": "16"},
        {"name": "W", "size": "16"},
        {"name": "X", "size": "16"},
    ],
    "23-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
        {"name": "32", "size": "22D"},
        {"name": "33", "size": "22D"},
        {"name": "34", "size": "22D"},
        {"name": "35", "size": "22D"},
        {"name": "36", "size": "22D"},
        {"name": "37", "size": "22D"},
        {"name": "38", "size": "22D"},
        {"name": "39", "size": "22D"},
        {"name": "40", "size": "22D"},
        {"name": "41", "size": "22D"},
        {"name": "42", "size": "22D"},
        {"name": "43", "size": "22D"},
        {"name": "44", "size": "22D"},
        {"name": "45", "size": "22D"},
        {"name": "46", "size": "22D"},
        {"name": "47", "size": "22D"},
        {"name": "48", "size": "22D"},
        {"name": "49", "size": "22D"},
        {"name": "50", "size": "22D"},
        {"name": "51", "size": "22D"},
        {"name": "52", "size": "22D"},
        {"name": "53", "size": "22D"},
        {"name": "54", "size": "22D"},
        {"name": "55", "size": "22D"},
        {"name": "56", "size": "22D"},
        {"name": "57", "size": "22D"},
        {"name": "58", "size": "22D"},
        {"name": "59", "size": "22D"},
        {"name": "60", "size": "22D"},
        {"name": "61", "size": "22D"},
        {"name": "62", "size": "22D"},
        {"name": "63", "size": "22D"},
        {"name": "64", "size": "22D"},
        {"name": "65", "size": "22D"},
        {"name": "66", "size": "22D"},
        {"name": "67", "size": "22D"},
        {"name": "68", "size": "22D"},
        {"name": "69", "size": "22D"},
        {"name": "70", "size": "22D"},
        {"name": "71", "size": "22D"},
        {"name": "72", "size": "22D"},
        {"name": "73", "size": "22D"},
        {"name": "74", "size": "22D"},
        {"name": "75", "size": "22D"},
        {"name": "76", "size": "22D"},
        {"name": "77", "size": "22D"},
        {"name": "78", "size": "22D"},
        {"name": "79", "size": "22D"},
        {"name": "80", "size": "22D"},
        {"name": "81", "size": "22D"},
        {"name": "82", "size": "22D"},
        {"name": "83", "size": "22D"},
        {"name": "84", "size": "22D"},
        {"name": "85", "size": "22D"},
        {"name": "86", "size": "22D"},
        {"name": "87", "size": "22D"},
        {"name": "88", "size": "22D"},
        {"name": "89", "size": "22D"},
        {"name": "90", "size": "22D"},
        {"name": "91", "size": "22D"},
        {"name": "92", "size": "22D"},
        {"name": "93", "size": "22D"},
        {"name": "94", "size": "22D"},
        {"name": "95", "size": "22D"},
        {"name": "96", "size": "22D"},
        {"name": "97", "size": "22D"},
        {"name": "98", "size": "22D"},
        {"name": "99", "size": "22D"},
        {"name": "100", "size": "22D"},
    ],
    "23-53": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "20"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "20"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "20"},
        {"name": "r", "size": "20"},
        {"name": "s", "size": "20"},
        {"name": "t", "size": "20"},
        {"name": "u", "size": "20"},
        {"name": "v", "size": "20"},
        {"name": "w", "size": "20"},
        {"name": "x", "size": "20"},
        {"name": "y", "size": "20"},
        {"name": "z", "size": "20"},
        {"name": "AA", "size": "20"},
        {"name": "BB", "size": "20"},
        {"name": "CC", "size": "20"},
        {"name": "DD", "size": "20"},
        {"name": "EE", "size": "20"},
        {"name": "FF", "size": "20"},
        {"name": "GG", "size": "20"},
        {"name": "HH", "size": "20"},
    ],
    "23-55": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "20"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "i", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "20"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "20"},
        {"name": "r", "size": "20"},
        {"name": "s", "size": "20"},
        {"name": "t", "size": "20"},
        {"name": "u", "size": "20"},
        {"name": "v", "size": "20"},
        {"name": "w", "size": "20"},
        {"name": "x", "size": "20"},
        {"name": "y", "size": "20"},
        {"name": "z", "size": "20"},
        {"name": "AA", "size": "20"},
        {"name": "BB", "size": "20"},
        {"name": "CC", "size": "20"},
        {"name": "DD", "size": "20"},
        {"name": "EE", "size": "20"},
        {"name": "FF", "size": "20"},
        {"name": "GG", "size": "20"},
        {"name": "HH", "size": "20"},
    ],
    "25-4": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "20"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "20"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "20"},
        {"name": "r", "size": "20"},
        {"name": "s", "size": "20"},
        {"name": "t", "size": "20"},
        {"name": "u", "size": "20"},
        {"name": "v", "size": "20"},
        {"name": "w", "size": "20"},
        {"name": "x", "size": "20"},
        {"name": "y", "size": "20"},
        {"name": "z", "size": "20"},
        {"name": "AA", "size": "20"},
        {"name": "BB", "size": "20"},
        {"name": "CC", "size": "20"},
        {"name": "DD", "size": "16"},
        {"name": "EE", "size": "16"},
        {"name": "FF", "size": "16"},
        {"name": "GG", "size": "16"},
        {"name": "HH", "size": "16"},
        {"name": "JJ", "size": "16"},
        {"name": "KK", "size": "20"},
        {"name": "LL", "size": "16"},
    ],
    "25-19": [
        {"name": "A", "size": "12"},
        {"name": "B", "size": "12"},
        {"name": "C", "size": "12"},
        {"name": "D", "size": "12"},
        {"name": "E", "size": "12"},
        {"name": "F", "size": "12"},
        {"name": "G", "size": "12"},
        {"name": "H", "size": "12"},
        {"name": "J", "size": "12"},
        {"name": "K", "size": "12"},
        {"name": "L", "size": "12"},
        {"name": "M", "size": "12"},
        {"name": "N", "size": "12"},
        {"name": "P", "size": "12"},
        {"name": "R", "size": "12"},
        {"name": "S", "size": "12"},
        {"name": "T", "size": "12"},
        {"name": "U", "size": "12"},
        {"name": "V", "size": "12"},
    ],
    "25-29": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
        {"name": "J", "size": "16"},
        {"name": "K", "size": "16"},
        {"name": "L", "size": "16"},
        {"name": "M", "size": "16"},
        {"name": "N", "size": "16"},
        {"name": "P", "size": "12"},
        {"name": "R", "size": "16"},
        {"name": "S", "size": "16"},
        {"name": "T", "size": "16"},
        {"name": "U", "size": "16"},
        {"name": "V", "size": "16"},
        {"name": "W", "size": "16"},
        {"name": "X", "size": "16"},
        {"name": "Y", "size": "16"},
        {"name": "Z", "size": "16"},
        {"name": "a", "size": "16"},
        {"name": "b", "size": "16"},
        {"name": "c", "size": "16"},
        {"name": "d", "size": "16"},
        {"name": "e", "size": "16"},
        {"name": "f", "size": "16"},
    ],
    "25-35": [
        {"name": "1", "size": "22D"},
        {"name": "2", "size": "22D"},
        {"name": "3", "size": "22D"},
        {"name": "4", "size": "22D"},
        {"name": "5", "size": "22D"},
        {"name": "6", "size": "22D"},
        {"name": "7", "size": "22D"},
        {"name": "8", "size": "22D"},
        {"name": "9", "size": "22D"},
        {"name": "10", "size": "22D"},
        {"name": "11", "size": "22D"},
        {"name": "12", "size": "22D"},
        {"name": "13", "size": "22D"},
        {"name": "14", "size": "22D"},
        {"name": "15", "size": "22D"},
        {"name": "16", "size": "22D"},
        {"name": "17", "size": "22D"},
        {"name": "18", "size": "22D"},
        {"name": "19", "size": "22D"},
        {"name": "20", "size": "22D"},
        {"name": "21", "size": "22D"},
        {"name": "22", "size": "22D"},
        {"name": "23", "size": "22D"},
        {"name": "24", "size": "22D"},
        {"name": "25", "size": "22D"},
        {"name": "26", "size": "22D"},
        {"name": "27", "size": "22D"},
        {"name": "28", "size": "22D"},
        {"name": "29", "size": "22D"},
        {"name": "30", "size": "22D"},
        {"name": "31", "size": "22D"},
        {"name": "32", "size": "22D"},
        {"name": "33", "size": "22D"},
        {"name": "34", "size": "22D"},
        {"name": "35", "size": "22D"},
        {"name": "36", "size": "22D"},
        {"name": "37", "size": "22D"},
        {"name": "38", "size": "22D"},
        {"name": "39", "size": "22D"},
        {"name": "40", "size": "22D"},
        {"name": "41", "size": "22D"},
        {"name": "42", "size": "22D"},
        {"name": "43", "size": "22D"},
        {"name": "44", "size": "22D"},
        {"name": "45", "size": "22D"},
        {"name": "46", "size": "22D"},
        {"name": "47", "size": "22D"},
        {"name": "48", "size": "22D"},
        {"name": "49", "size": "22D"},
        {"name": "50", "size": "22D"},
        {"name": "51", "size": "22D"},
        {"name": "52", "size": "22D"},
        {"name": "53", "size": "22D"},
        {"name": "54", "size": "22D"},
        {"name": "55", "size": "22D"},
        {"name": "56", "size": "22D"},
        {"name": "57", "size": "22D"},
        {"name": "58", "size": "22D"},
        {"name": "59", "size": "22D"},
        {"name": "60", "size": "22D"},
        {"name": "61", "size": "22D"},
        {"name": "62", "size": "22D"},
        {"name": "63", "size": "22D"},
        {"name": "64", "size": "22D"},
        {"name": "65", "size": "22D"},
        {"name": "66", "size": "22D"},
        {"name": "67", "size": "22D"},
        {"name": "68", "size": "22D"},
        {"name": "69", "size": "22D"},
        {"name": "70", "size": "22D"},
        {"name": "71", "size": "22D"},
        {"name": "72", "size": "22D"},
        {"name": "73", "size": "22D"},
        {"name": "74", "size": "22D"},
        {"name": "75", "size": "22D"},
        {"name": "76", "size": "22D"},
        {"name": "77", "size": "22D"},
        {"name": "78", "size": "22D"},
        {"name": "79", "size": "22D"},
        {"name": "80", "size": "22D"},
        {"name": "81", "size": "22D"},
        {"name": "82", "size": "22D"},
        {"name": "83", "size": "22D"},
        {"name": "84", "size": "22D"},
        {"name": "85", "size": "22D"},
        {"name": "86", "size": "22D"},
        {"name": "87", "size": "22D"},
        {"name": "88", "size": "22D"},
        {"name": "89", "size": "22D"},
        {"name": "90", "size": "22D"},
        {"name": "91", "size": "22D"},
        {"name": "92", "size": "22D"},
        {"name": "93", "size": "22D"},
        {"name": "94", "size": "22D"},
        {"name": "95", "size": "22D"},
        {"name": "96", "size": "22D"},
        {"name": "97", "size": "22D"},
        {"name": "98", "size": "22D"},
        {"name": "99", "size": "22D"},
        {"name": "100", "size": "22D"},
        {"name": "101", "size": "22D"},
        {"name": "102", "size": "22D"},
        {"name": "103", "size": "22D"},
        {"name": "104", "size": "22D"},
        {"name": "105", "size": "22D"},
        {"name": "106", "size": "22D"},
        {"name": "107", "size": "22D"},
        {"name": "108", "size": "22D"},
        {"name": "109", "size": "22D"},
        {"name": "110", "size": "22D"},
        {"name": "111", "size": "22D"},
        {"name": "112", "size": "22D"},
        {"name": "113", "size": "22D"},
        {"name": "114", "size": "22D"},
        {"name": "115", "size": "22D"},
        {"name": "116", "size": "22D"},
        {"name": "117", "size": "22D"},
        {"name": "118", "size": "22D"},
        {"name": "119", "size": "22D"},
        {"name": "120", "size": "22D"},
        {"name": "121", "size": "22D"},
        {"name": "122", "size": "22D"},
        {"name": "123", "size": "22D"},
        {"name": "124", "size": "22D"},
        {"name": "125", "size": "22D"},
        {"name": "126", "size": "22D"},
        {"name": "127", "size": "22D"},
        {"name": "128", "size": "22D"},
    ],
    "25-37": [
        {"name": "A", "size": "16"},
        {"name": "B", "size": "16"},
        {"name": "C", "size": "16"},
        {"name": "D", "size": "16"},
        {"name": "E", "size": "16"},
        {"name": "F", "size": "16"},
        {"name": "G", "size": "16"},
        {"name": "H", "size": "16"},
        {"name": "J", "size": "16"},
        {"name": "K", "size": "16"},
        {"name": "L", "size": "16"},
        {"name": "M", "size": "16"},
        {"name": "N", "size": "16"},
        {"name": "P", "size": "12"},
        {"name": "R", "size": "16"},
        {"name": "S", "size": "16"},
        {"name": "T", "size": "16"},
        {"name": "U", "size": "16"},
        {"name": "V", "size": "16"},
        {"name": "W", "size": "16"},
        {"name": "X", "size": "16"},
        {"name": "Y", "size": "16"},
        {"name": "Z", "size": "16"},
        {"name": "a", "size": "16"},
        {"name": "b", "size": "16"},
        {"name": "c", "size": "16"},
        {"name": "d", "size": "16"},
        {"name": "e", "size": "16"},
        {"name": "f", "size": "16"},
        {"name": "g", "size": "16"},
        {"name": "h", "size": "16"},
        {"name": "k", "size": "16"},
        {"name": "l", "size": "16"},
        {"name": "m", "size": "16"},
        {"name": "n", "size": "16"},
        {"name": "p", "size": "12"},
        {"name": "r", "size": "16"},
    ],
    "25-61": [
        {"name": "A", "size": "20"},
        {"name": "B", "size": "20"},
        {"name": "C", "size": "20"},
        {"name": "D", "size": "20"},
        {"name": "E", "size": "20"},
        {"name": "F", "size": "20"},
        {"name": "G", "size": "20"},
        {"name": "H", "size": "20"},
        {"name": "J", "size": "20"},
        {"name": "K", "size": "20"},
        {"name": "L", "size": "20"},
        {"name": "M", "size": "20"},
        {"name": "N", "size": "20"},
        {"name": "P", "size": "16"},
        {"name": "R", "size": "20"},
        {"name": "S", "size": "20"},
        {"name": "T", "size": "20"},
        {"name": "U", "size": "20"},
        {"name": "V", "size": "20"},
        {"name": "W", "size": "20"},
        {"name": "X", "size": "20"},
        {"name": "Y", "size": "20"},
        {"name": "Z", "size": "20"},
        {"name": "a", "size": "20"},
        {"name": "b", "size": "20"},
        {"name": "c", "size": "20"},
        {"name": "d", "size": "20"},
        {"name": "e", "size": "20"},
        {"name": "f", "size": "20"},
        {"name": "g", "size": "20"},
        {"name": "h", "size": "20"},
        {"name": "i", "size": "20"},
        {"name": "j", "size": "20"},
        {"name": "k", "size": "20"},
        {"name": "l", "size": "20"},
        {"name": "m", "size": "20"},
        {"name": "n", "size": "20"},
        {"name": "p", "size": "16"},
        {"name": "r", "size": "20"},
        {"name": "s", "size": "20"},
        {"name": "t", "size": "20"},
        {"name": "u", "size": "20"},
        {"name": "v", "size": "20"},
        {"name": "w", "size": "20"},
        {"name": "x", "size": "20"},
        {"name": "y", "size": "20"},
        {"name": "z", "size": "20"},
        {"name": "AA", "size": "20"},
        {"name": "BB", "size": "20"},
        {"name": "CC", "size": "20"},
        {"name": "DD", "size": "20"},
        {"name": "EE", "size": "20"},
        {"name": "FF", "size": "20"},
        {"name": "GG", "size": "20"},
        {"name": "HH", "size": "20"},
        {"name": "JJ", "size": "20"},
        {"name": "KK", "size": "20"},
        {"name": "LL", "size": "20"},
        {"name": "MM", "size": "20"},
        {"name": "NN", "size": "20"},
        {"name": "PP", "size": "20"},
    ]
}

STANDARD_CSYS_CHILDREN = {
    "flagnote-1": {"angle": 0, "distance": 3, "rotation": 0},
    "flagnote-1-leader_dest": {"angle": 0, "distance": 1, "rotation": 0},
    "flagnote-2": {"angle": 15, "distance": 3, "rotation": 0},
    "flagnote-2-leader_dest": {"angle": 15, "distance": 1.03, "rotation": 0},
    "flagnote-3": {"angle": -15, "distance": 3, "rotation": 0},
    "flagnote-3-leader_dest": {"angle": -15, "distance": 1.03, "rotation": 0},
    "flagnote-4": {"angle": 30, "distance": 3, "rotation": 0},
    "flagnote-4-leader_dest": {"angle": 30, "distance": 1, "rotation": 0},
    "flagnote-5": {"angle": -30, "distance": 3, "rotation": 0},
    "flagnote-5-leader_dest": {"angle": -30, "distance": 1, "rotation": 0},
    "flagnote-6": {"angle": 45, "distance": 3, "rotation": 0},
    "flagnote-6-leader_dest": {"angle": 45, "distance": 0.72, "rotation": 0},
    "flagnote-7": {"angle": -45, "distance": 3, "rotation": 0},
    "flagnote-7-leader_dest": {"angle": -45, "distance": 0.72, "rotation": 0},
    "flagnote-8": {"angle": 60, "distance": 3, "rotation": 0},
    "flagnote-8-leader_dest": {"angle": 60, "distance": 0.58, "rotation": 0},
    "flagnote-9": {"angle": -60, "distance": 3, "rotation": 0},
    "flagnote-9-leader_dest": {"angle": -60, "distance": 0.58, "rotation": 0},
    "flagnote-10": {"angle": -75, "distance": 3, "rotation": 0},
    "flagnote-10-leader_dest": {"angle": -75, "distance": 0.52, "rotation": 0},
    "flagnote-11": {"angle": 75, "distance": 3, "rotation": 0},
    "flagnote-11-leader_dest": {"angle": 75, "distance": 0.52, "rotation": 0},
    "flagnote-12": {"angle": -90, "distance": 3, "rotation": 0},
    "flagnote-12-leader_dest": {"angle": -90, "distance": 0.52, "rotation": 0},
    "flagnote-13": {"angle": 90, "distance": 3, "rotation": 0},
    "flagnote-13-leader_dest": {"angle": 90, "distance": 0.5, "rotation": 0},
}

def series_iii_26_connector_svg(part_number, shell_size):
    """
    Generate a simple SVG drawing of a Series III 26 connector based on shell size.
    
    Args:
        part_number: Part number string for the connector
        shell_size: Shell size letter ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', or 'J')
    
    Returns:
        str: SVG markup as a string
    """
    
    # Connector specifications from the technical drawing
    specs = {
        'A': {'q_max': 21.8, 'length': 31.34, 'numeric': 9},
        'B': {'q_max': 25.0, 'length': 31.34, 'numeric': 11},
        'C': {'q_max': 29.4, 'length': 31.34, 'numeric': 13},
        'D': {'q_max': 32.5, 'length': 31.34, 'numeric': 15},
        'E': {'q_max': 35.7, 'length': 31.34, 'numeric': 17},
        'F': {'q_max': 38.5, 'length': 31.34, 'numeric': 19},
        'G': {'q_max': 41.7, 'length': 31.34, 'numeric': 21},
        'H': {'q_max': 44.9, 'length': 31.34, 'numeric': 23},
        'J': {'q_max': 48.0, 'length': 31.34, 'numeric': 25}
    }
    
    if shell_size not in specs:
        raise ValueError(f"Shell size must be one of {list(specs.keys())}")
    
    spec = specs[shell_size]
    
    # Scale factor
    scale = 3.0
    
    # Overall dimensions
    length = spec['length'] * scale
    diameter = spec['q_max'] * scale
    half_diameter = diameter / 2
    
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="400" height="400">
<g id="{part_number}-drawing-contents-start">
<rect x="0" y="{-half_diameter}" width="{length}" height="{diameter}" fill="#C0C0C0" stroke="black" stroke-width="2"/>
</g>
<g id="{part_number}-drawing-contents-end">
</g>
</svg>'''
    
    return svg


def compile_part_attributes(part_configuration):
    pn_arrangement = part_configuration.get("insert_arrangement")
    pn_arrangement_prefix = pn_arrangement[0]
    pn_arrangement_suffix = pn_arrangement[1:]

    if pn_arrangement_prefix == "A":
        shell_size = "9"
    elif pn_arrangement_prefix == "B":
        shell_size = "11"
    elif pn_arrangement_prefix == "C":
        shell_size = "13"
    elif pn_arrangement_prefix == "D":
        shell_size = "15"
    elif pn_arrangement_prefix == "E":
        shell_size = "17"
    elif pn_arrangement_prefix == "F":
        shell_size = "19"
    elif pn_arrangement_prefix == "G":
        shell_size = "21"
    elif pn_arrangement_prefix == "H":
        shell_size = "23"
    elif pn_arrangement_prefix == "J":
        shell_size = "25"

    else:
        raise ValueError(f"Invalid insert arrangement prefix: {pn_arrangement_prefix}")

    insert_arrangement = f"{shell_size}-{pn_arrangement_suffix}"
    
    # FIND CONTACTS
    contacts = INSERT_ARRANGEMENTS.get(insert_arrangement)

    # FIND UNIQUE CONTACT SIZES
    seen_contact_sizes = []
    for contact in contacts:
        if contact.get("size") not in seen_contact_sizes:
            seen_contact_sizes.append(contact.get("size"))

    # FIND RELEVANT TOOLS
    tools = []
    for contact_size in seen_contact_sizes:
        tools.append(f"{CONTACT_SIZES.get(contact_size).get('crimp_tool')} crimp tool")
        tools.append(f"{CONTACT_SIZES.get(contact_size).get('extraction_tool')} extraction tool")

    attributes = {
        "tools": tools,
        "build_notes": [],
        "csys_children": STANDARD_CSYS_CHILDREN,
        "contacts": contacts,
        "shell_size": part_configuration.get("insert_arrangement")[0],
    }
    return attributes


def main():
    state.set_rev(REVISION)
    state.set_product("part")

    part_configurations = []
    for shell_type in ["26"]:
        for finish in ["F", "K", "W", "Z"]:
            for insert_arrangement in [
                "A35",
                "A98",
                "B5",
                "B35",
                "B99",
                "C35",
                "C98",
                "D5",
                "D19",
                "D35",
                "E6",
                "E8",
                "E26",
                "E35",
                "F11",
                "F32",
                "F35",
                "G11",
                "G16",
                "G35",
                "G41",
                "H21",
                "H35",
                "H55",
                "J19",
                "J29",
                "J35",
                "J61",
            ]:
                for contact_type in ["P", "S"]:
                    for key in ["N", "A", "B", "C"]:
                        part_configurations.append(
                            {
                                "shell_type": shell_type,
                                "finish": finish,
                                "insert_arrangement": insert_arrangement,
                                "contact_type": contact_type,
                                "key": key,
                            }
                        )

    for part_configuration in part_configurations:
        # GENERATE THE PART NUMBER
        part_number = f"D38999_{part_configuration['shell_type']}{part_configuration['finish']}{part_configuration['insert_arrangement']}{part_configuration['contact_type']}{part_configuration['key']}"
        print("Preparing part number: ", part_number)

        # MAKE THE PART FOLDER
        part_dir = os.path.join(os.getcwd(), part_number)
        os.makedirs(part_dir, exist_ok=True)

        # UPDATE THE REVISION HISTORY FILE
        revision_history_content_dict = {
            "product": state.product,
            "mfg": "mil spec",
            "pn": part_number,
            "rev": REVISION,
            "desc": "",
            "status": "",
            "datestarted": DATE_STARTED,
            "library_repo": "https://github.com/harnice/d38999",
            "library_subpath": "Connector"
        }
        revision_history_csv_path = os.path.join(
            part_dir, f"{part_number}-revision_history.tsv"
        )
        rev_history.part_family_append(
            revision_history_content_dict, revision_history_csv_path
        )

        # CLEAN AND MAKE THE REVISION FOLDER
        rev_dir = os.path.join(part_dir, f"{part_number}-rev{REVISION}")
        if os.path.exists(rev_dir):
            for item in os.listdir(rev_dir):
                item_path = os.path.join(rev_dir, item)
                if os.path.isfile(item_path):
                    os.remove(item_path)
        else:
            os.makedirs(rev_dir)

        # WRITE THE ATTRIBUTES JSON
        json_path = os.path.join(
            rev_dir, f"{part_number}-rev{REVISION}-attributes.json"
        )
        attributes = compile_part_attributes(part_configuration)
        with open(json_path, "w") as f:
            json.dump(attributes, f, indent=2)


        # GENERATE THE SVG
        if part_configuration.get("shell_type") == "26":
            svg_content = series_iii_26_connector_svg(part_number, attributes.get("shell_size"))
            svg_path = os.path.join(rev_dir, f"{part_number}-rev{REVISION}-drawing.svg")
            with open(svg_path, "w") as f:
                f.write(svg_content)

        
        # RENDER THE PART
        subprocess.run(['harnice', '-r'], cwd=rev_dir, check=True)

    print("Finished rendering all parts in family.")

if __name__ == "__main__":
    main()
